.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" This manpage is Copyright (C) 1999 Tim Martin
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\"
.TH sasl_usererr "26 March 2000" SASL "SASL man pages"
.SH NAME
sasl_usererr \- Translate server error code to user error code


.SH SYNOPSIS
.nf
.B #include <sasl.h>

.sp
.BI "int sasl_usererr(" int " saslerr )";

.fi
.SH DESCRIPTION

.B sasl_usererr
translates server error code to user error code. Currently only maps
SASL_NOUSER to SASL_BADAUTH.

.PP

.SH "RETURN VALUE"

Returns user error code.

.SH "CONFORMING TO"
RFC 2222
.SH "SEE ALSO"
.BR other sasl stuff
.BR 
.BR 