.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" This manpage is Copyright (C) 1999 Tim Martin
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\"
.TH sasl_dispose "26 March 2000" SASL "SASL man pages"
.SH NAME
sasl_dispose \- Dispose of a SASL connection object


.SH SYNOPSIS
.nf
.B #include <sasl.h>

.sp
.BI "void sasl_dispose(" sasl_conn_t " **pconn )";

.fi
.SH DESCRIPTION

.B sasl_dispose
is called when a SASL connection object is no longer needed. Note that
this is usually when the protocol session is done NOT when the
authentication is done since a security layer may have been
negotiated.

.PP

.SH "RETURN VALUE"

No return values

.SH "CONFORMING TO"
RFC 2222
.SH "SEE ALSO"
.BR other sasl stuff
.BR 
.BR 