.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" This manpage is Copyright (C) 1999 Tim Martin
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\"
.TH SASL "26 March 2000" SASL "SASL man pages"
.SH NAME
SASL \- SASL authentication library
.SH DESCRIPTION
The CMU Cyrus SASL library is a general purpose authentication library for sever and client applications.

.B System Administrators:

For information on setting up/configuring the SASL library see the 
.I System Administrators Guide
in the doc/ directory of the SASL distribution.

.B Programmers:

See man pages for individual sasl functions or the
.I Programmers Guide
in the doc/ directory of the SASL distribution.
.SH "CONFORMING TO"
RFC 2222
.SH "SEE ALSO"
sasl_authorize_t(3), sasl_callbacks(3), sasl_checkpass(3), sasl_client_init(3), sasl_client_new(3), sasl_client_start(3), sasl_client_step(3), sasl_decode(3), sasl_done(3), sasl_encode(3), sasl_errstring(3), sasl_getopt_t(3), sasl_getpath_t(3), sasl_setprop(3), sasl_getsecret_t(3), sasl_getsimple_t(3), sasl_listmech(3), sasl_log_t(3), sasl_server_init(3), sasl_server_new(3), sasl_server_start(3), sasl_server_step(3), sasl_setprop(3), sasl_usererr(3)