language: c
sudo: required
dist: trusty
group: edge

os:
  - linux
  - osx
compiler: gcc

before_script:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install ccache; fi
  - ccache --version
  - ccache --zero-stats
  - ./autogen.sh
  - make
script:
  - make check
branches:
  only:
    - master
