language: c
sudo: required
dist: trusty
group: edge

os:
  - linux
  - osx
compiler: gcc

# For OS X, but shouldn't cause any problems on Linux
cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_script:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install ccache; fi
  - ccache --version
  - ccache --zero-stats
  - ./autogen.sh
  - make
script:
  - make check
branches:
  only:
    - master
