.\" sasldbconverter-2 - Convert sasldb file into the new format
.\" Dima Barsky 25/10/2002
.\"

.\"
.TH SASLDBCONVERTER2 8 "October 25, 2002" "CMU SASL"
.SH NAME
sasldbconverter2 \- Convert sasldb file into the new format
.SH SYNOPSIS
.B sasldbconverter2 [sasldb_file]
.SH DESCRIPTION
.I sasldbconverter2
takes the sasldb file specified on the
command line and convert it to a new sasldb file in the default
location (usually /etc/sasldb2). It is STRONGLY RECOMMENDED that you
backup sasldb before allowing this program to run
.SH OPTIONS
.TP
.SH KNOWN BUGS
This only works for sasldb files that use the gdbm library.
.TP
.SH SEE ALSO
rfc2222 \- Simple Authentication and Security Layer (SASL)
